server:
  port: 8080
spring:
  application:
    name: tool
  ai:
    openai:
      api-key: ${API_KEY}
      base-url: https://api.deepseek.com/v1
      chat:
        options:
          model: deepseek-chat
          temperature: 1.0
          max-tokens: 2048

logging:
  config: classpath:logback.xml

