server:
  port: 8080
spring:
  application:
    name: tool
  main:
    web-application-type: none
  ai:
    openai:
      api-key: ${API_KEY}
      base-url: https://api.deepseek.com
      chat:
        options:
          model: deepseek-chat
          temperature: 1.0
          max-tokens: 2048

logging:
  config: classpath:logback.xml
  level:
    org.springframework.ai: DEBUG
    reactor.netty.http.client: DEBUG
